"""Add posts table with user relationship one to one

Revision ID: 019a8737f705
Revises: 74e2381a83fb
Create Date: 2025-05-15 02:10:17.289286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019a8737f705'
down_revision = '74e2381a83fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
