"""added access_token_encrypted column

Revision ID: 15ea2f508191
Revises: bfba9165c5ac
Create Date: 2025-05-21 05:42:28.771387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ea2f508191'
down_revision = 'bfba9165c5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token_encrypted', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('access_token_encrypted')

    # ### end Alembic commands ###
