"""Add provider, provider_id columns to users table

Revision ID: 42240455bcc4
Revises: 45d4ba28c417
Create Date: 2025-05-21 03:07:13.787543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42240455bcc4'
down_revision = '45d4ba28c417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('provider_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('provider_id')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
