"""empty message

Revision ID: bfba9165c5ac
Revises: 42240455bcc4
Create Date: 2025-05-21 04:39:53.009685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfba9165c5ac'
down_revision = '42240455bcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_encrypted', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('refresh_token_encrypted')

    # ### end Alembic commands ###
